service: sctp-serverless-i-leon
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
  apipost:
    handler: index.handlerpost
    events:
      - httpApi:
          path: /
          method: post

plugins:
  - serverless-offline